name: CI (Nx + Jest)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testapp
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
     
      - name: Install root deps
        run: npm install

      - name: Backend Prisma setup
        working-directory: apps/backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testapp?schema=public
          CORS_ORIGIN: http://localhost:4200
          SESSION_SECRET: test-secret
        run: |
          cp .env.example .env
          npm install
          npm run prisma:generate
          npm run prisma:migrate

      - name: Run Nx tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testapp?schema=public
          CORS_ORIGIN: http://localhost:4200
          SESSION_SECRET: test-secret
        run: npx nx run-many -t test --all
